default-repository: $DEFAULT_REPOSITORY

#badgerfish-rules-location: file:/tmp/badger-fish-rules.yaml

repository-names:
    corepo:
        - corepo
        - $DEFAULT_REPOSITORY
    rawrepo:
        - rawrepo
    
# as used by badgerfish output and InfoRequest  
default-namespaces:
    ac: "http://biblstandard.dk/ac/namespace/"
    dbcaddi: "http://oss.dbc.dk/rdf/dbcaddi#"
    dbcbib: "http://oss.dbc.dk/rdf/dbcbib#"
    dc: "http://purl.org/dc/elements/1.1/"
    dcmitype: "http://purl.org/dc/dcmitype/"
    dcterms: "http://purl.org/dc/terms/"
    dkabm: "http://biblstandard.dk/abm/namespace/dkabm/"
    dkdcplus: "http://biblstandard.dk/abm/namespace/dkdcplus/"
    docbook: "http://docbook.org/ns/docbook"
    kml: "http://www.opengis.net/kml/2.2"
    marcx: "info:lc/xmlns/marcxchange-v1"
    mx: "http://www.loc.gov/MARC21/slim"
    of: "http://oss.dbc.dk/ns/openformat"
    ofo: "http://oss.dbc.dk/ns/openformatoutput"
    os: "http://oss.dbc.dk/ns/opensearch"
    oso: "http://oss.dbc.dk/ns/opensearchobjects"
    oss: "http://oss.dbc.dk/ns/osstypes"
    soap: "http://schemas.xmlsoap.org/soap/envelope/"
    xs: "http://www.w3.org/2001/XMLSchema"
    xsi: "http://www.w3.org/2001/XMLSchema-instance"

# Configuration of timeout for each cache type
j-cache:
    openagency: CREATED:10m
    work: ACCESSED:5m


x-forwarded-for: $X_FORWARDED_FOR

http-client:
    connect-timeout: 2500ms
    read-timeout: 2m

user-messages:
    BACKEND_CONTENT_SERVICE: "Error retrieving record content"
    BACKEND_SOLR: "Error performing search"
    BAD_PROFILE: "An unknown profile is used"
    INTERNAL_SERVER_ERROR: "Internal server error"
    MALFORMED_REQUEST: "The request couldn't be decoded"
    UNKNOWN_REPOSITORY: "The specified repository is unknown"